%YAML 1.2
---

# FIRST DRAFT of SOLEIL px2 configuration. TO BE EDITED

# The class to initialise, and init parameters
_initialise_class:
  class: mxcubecore.HardwareObjects.Beamline.Beamline
  # Further key-value pairs here will be passed to the class init
  # mode: devel

# objects
#
# Eventually all objects should use the yaml config system like Beamline,
# but for now we can leave them as xml
#
# NBNB some objects that do not currently have their own config files
# would need those added (e.g. the centring methods)
#
_objects:
  # The !!o0map and the lines starting with '- ' give you an *orderd* dictionary
  # And thus a reproducible loading order
  !!omap
  # The values are the file paths to the configuration file for the
  # object, relative to the configuration file path(s)
  #
  # NB - the order is *NOT* arbitrary, as signal connnections are set
  # on one object that require the other to be already loaded.
  #
  # Hardware:
  - session: singleton_objects/session.xml
  # - machine_info: mach.xml
  - transmission: singleton_motors/transmission.xml
  - energy: singleton_motors/photon_energy.xml
  - beam: singleton_objects/beaminfo_exporter.xml
  # - flux: flux.xml
  - detector: mockups/detector-mockup.xml
  - resolution: singleton_motors/resolution.xml
  # - hutch_interlock: door-interlock-mockup.xml
  # - safety_shutter: safety_shutter.xml
  # - fast_shutter: fastshut.xml
  - sample_changer: singleton_objects/cats.xml
  # NBNB TODO remove plate_manipulater and treat as another smaple changer
  # - plate_manipulator: plate-manipulator.xml
  - diffractometer: diffractometer/diffractometer.xml
  - graphics: singleton_objects/Qt4_graphics-manager.xml
  - lims: singleton_objects/dbconnection.xml
  # - queue_manager: queue.xml
  # - queue_model: queue-model.xml
  # Procedures:
  - collect: experimental_methods/diffraction_methods.xml
  - xrf_spectrum: mockups/xrf-spectrum-mockup.xml
  - energy_scan: mockups/energyscan-mockup.xml
  #    - imaging: xray-imaging.xml # Only in EMBL as of 201907
  - gphl_workflow: gphl-workflow.xml
  - gphl_connection: gphl-setup.xml
  # - centring: centring.xml
  # Analysis:
  # - offline_processing: auto-processing.xml
  # - online_processing: parallel-processing.xml
  - characterisation: singleton_objects/data-analysis.xml
  # - beam_realign: # Skipped - optional

# Non-object attributes:
advanced_methods:
  - MeshScan
  - XrayCentering
  - LineScsn

tunable_wavelength: true
disable_num_passes: false
run_number: 1

default_acquisition_parameters:
  default:
    # Default values, also used for standard acquisition.
    # Values not given in other dictionaries are taken from here
    exp_time: 0.025             # (s) exposure time
    osc_start: 0.0              # (degrees) Only used if no current angle found
    osc_range: 0.1              # (degrees)
    num_passes: 1               # (int)
    first_image: 1              # (int)
    overlap: 0
    num_images: 1800            # (int)
    # detector_binning_mode: 1          # Removed as not in practice used.
    inverse_beam: false         # (bool)
    take_dark_current: true     # (bool)
    skip_existing_images: true  # (bool)
    take_snapshots: true        # (bool)

  # helical:
  #   # Defaults for helical scan. Missing values are taken from default
  #   num_images: 100

  characterisation:
    # Defaults for chareacterisation. Missing values are taken from default
    overlap: -89
    wedge_size: 10        # (int)

  advanced:
    # Defaults for 'advanced' acquisition. Missing values are taken from default
    osc_range: 0.5
    num_images: 100

acquisition_limit_values:
  exposure_time:     # (s)
    - 0.00134
    - 6000.0
  osc_range:         # (degrees)
    - -1000.0
    - 10000.0
  number_of_images:  # (int)
    - 1
    - 99999
  kappa:             # (degrees)
    - -9.0
    - 240.0
# kappa_phi:         # (degrees)
#     - 0.0
#     - 360.0
