%YAML 1.2
---

# FIRST DRAFT of EMBL P14 configuration. TO BE EDITED

# The class to initialise, and init parameters
_initialise_class:
  class: mxcubecore.HardwareObjects.EMBL.EMBLBeamline.EMBLBeamline
  # Further key-value pairs here will be passed to the class init
  # mode: devel

# objects
#
# Eventually all objects should use the yaml config system like Beamline,
# but for now we can leave them as xml
#
# NBNB some objects that do not currently have their own config files
# would need those added (e.g. the centring methods)
#
_objects:
  # The !!o0map and the lines starting with '- ' give you an *orderd* dictionary
  # And thus a reproducible loading order
  !!omap
  # The values are the file paths to the configuration file for the
  # object, relative to the configuration file path(s)
  #
  # NB - the order is *NOT* arbitrary, as signal connnections are set
  # on one object that require the other to be already loaded.
  #
  # Hardware:
  - session: session.xml
  - machine_info: mach-info.xml
  - transmission: attenuators.xml
  - energy: energy.xml
  - flux: flux.xml
  - detector: eh1/detector.xml
  - resolution: eh1/resolution.xml
  # EMBL-specific - put before beam as connection is set in beam.
  - beam_definer: eh1/beamFocusing.xml
  - beam: beam-info.xml
  - hutch_interlock: door-interlock.xml
  - safety_shutter: safshut.xml
  - fast_shutter: fast-shut.xml
  - sample_changer: sc-generic.xml
  # NBNB TODO remove plate_manipulater and treat as another smaple changer
  - plate_manipulator: plate-manipulator.xml
  - diffractometer: mini-diff-mockup.xml
  - graphics: graphics.xml
  - lims: dbconnection.xml
  - queue_manager: queue.xml
  - queue_model: queue-model.xml
  # Procedures:
  - collect: mxcollect.xml
  - xrf_spectrum: xrf-spectrum.xml
  - energy_scan: energyscan.xml
  - imaging: xray-imaging.xml
  - image_tracking: image-tracking.xml
  - gphl_workflow: gphl-workflow.xml
  - gphl_connection: gphl-setup.xml
  # - centring: centring.xml
  # Analysis:
  - offline_processing: auto-processing.xml
  - online_processing: parallel-processing.xml
  - characterisation: data-analysis.xml
  # - beam_realign: # Skipped - optional
  # EMBL-specific:
  - ppu_control: ppu_control.xml

# Non-object attributes:
advanced_methods:
  - MeshScan
  - XrayCentering

tunable_wavelength: true
disable_num_passes: false
run_online_processing: true
run_number: 1

default_acquisition_parameters:
  default:
    # Default values, also used for standard acquisition.
    # Values not given in other dictionaries are taken from here
    exp_time: 0.01        # exposure time
    osc_start: 0.0  # Only used if no current angle can be found
    osc_range: 0.1
    num_passes: 1
    first_image: 1
    overlap: 0
    num_images: 1
    # detector_binning_mode: 1 # Removed as not in practice used.
    inverse_beam: false
    take_dark_current: true
    skip_existing_images: true
    take_snapshots: true
    # NB 'compression' not added as apparently never used

  helical:
    # Defaults for helical scan. Missing values are taken from default
    number_of_images: 100

  characterisation:
    # Defaults for chareacterisation. Missing values are taken from default
    exp_time: 0.04       # exposure time
    osc_range: 0.0062

  advanced:
    # Defaults for 'advanced' acquisition. Missing values are taken from default
    exp_time: 0.0014       # exposure time
    range: 0.5
    num_images: 100

  imaging:
    osc_range: 1.0
    num_images: 360
    # detector_binning_mode: "0"

acquisition_limit_values:
  number_of_images:
    - 1
    - 99999
  kappa:
    - -5.0
    - 240.0
