"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from mxcubecore.utils.pyispyb_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from mxcubecore.utils.pyispyb_client.exceptions import ApiAttributeError


def lazy_import():
    from mxcubecore.utils.pyispyb_client.model.crystal_composition_response import CrystalCompositionResponse
    from mxcubecore.utils.pyispyb_client.model.pydantic_main_protein import PydanticMainProtein
    globals()['CrystalCompositionResponse'] = CrystalCompositionResponse
    globals()['PydanticMainProtein'] = PydanticMainProtein


class CrystalResponse(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'crystal_id': (int,),  # noqa: E501
            'protein_id': (int,),  # noqa: E501
            'record_time_stamp': (datetime,),  # noqa: E501
            'protein': (PydanticMainProtein,),  # noqa: E501
            'crystal_compositions': ([CrystalCompositionResponse],),  # noqa: E501
            'diffraction_plan_id': (int,),  # noqa: E501
            'crystal_uuid': (str,),  # noqa: E501
            'name': (str,),  # noqa: E501
            'space_group': (str,),  # noqa: E501
            'morphology': (str,),  # noqa: E501
            'color': (str,),  # noqa: E501
            'size_x': (float,),  # noqa: E501
            'size_y': (float,),  # noqa: E501
            'size_z': (float,),  # noqa: E501
            'cell_a': (float,),  # noqa: E501
            'cell_b': (float,),  # noqa: E501
            'cell_c': (float,),  # noqa: E501
            'cell_alpha': (float,),  # noqa: E501
            'cell_beta': (float,),  # noqa: E501
            'cell_gamma': (float,),  # noqa: E501
            'comments': (str,),  # noqa: E501
            'pdb_file_name': (str,),  # noqa: E501
            'pdb_file_path': (str,),  # noqa: E501
            'abundance': (float,),  # noqa: E501
            'packing_fraction': (float,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'crystal_id': 'crystalId',  # noqa: E501
        'protein_id': 'proteinId',  # noqa: E501
        'record_time_stamp': 'recordTimeStamp',  # noqa: E501
        'protein': 'Protein',  # noqa: E501
        'crystal_compositions': 'crystal_compositions',  # noqa: E501
        'diffraction_plan_id': 'diffractionPlanId',  # noqa: E501
        'crystal_uuid': 'crystalUUID',  # noqa: E501
        'name': 'name',  # noqa: E501
        'space_group': 'spaceGroup',  # noqa: E501
        'morphology': 'morphology',  # noqa: E501
        'color': 'color',  # noqa: E501
        'size_x': 'size_X',  # noqa: E501
        'size_y': 'size_Y',  # noqa: E501
        'size_z': 'size_Z',  # noqa: E501
        'cell_a': 'cell_a',  # noqa: E501
        'cell_b': 'cell_b',  # noqa: E501
        'cell_c': 'cell_c',  # noqa: E501
        'cell_alpha': 'cell_alpha',  # noqa: E501
        'cell_beta': 'cell_beta',  # noqa: E501
        'cell_gamma': 'cell_gamma',  # noqa: E501
        'comments': 'comments',  # noqa: E501
        'pdb_file_name': 'pdbFileName',  # noqa: E501
        'pdb_file_path': 'pdbFilePath',  # noqa: E501
        'abundance': 'abundance',  # noqa: E501
        'packing_fraction': 'packingFraction',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, crystal_id, protein_id, record_time_stamp, protein, crystal_compositions, *args, **kwargs):  # noqa: E501
        """CrystalResponse - a model defined in OpenAPI

        Args:
            crystal_id (int):
            protein_id (int):
            record_time_stamp (datetime):
            protein (PydanticMainProtein):
            crystal_compositions ([CrystalCompositionResponse]):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            diffraction_plan_id (int): [optional]  # noqa: E501
            crystal_uuid (str): [optional]  # noqa: E501
            name (str): [optional]  # noqa: E501
            space_group (str): [optional]  # noqa: E501
            morphology (str): [optional]  # noqa: E501
            color (str): [optional]  # noqa: E501
            size_x (float): [optional]  # noqa: E501
            size_y (float): [optional]  # noqa: E501
            size_z (float): [optional]  # noqa: E501
            cell_a (float): [optional]  # noqa: E501
            cell_b (float): [optional]  # noqa: E501
            cell_c (float): [optional]  # noqa: E501
            cell_alpha (float): [optional]  # noqa: E501
            cell_beta (float): [optional]  # noqa: E501
            cell_gamma (float): [optional]  # noqa: E501
            comments (str): [optional]  # noqa: E501
            pdb_file_name (str): [optional]  # noqa: E501
            pdb_file_path (str): [optional]  # noqa: E501
            abundance (float): [optional]  # noqa: E501
            packing_fraction (float): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.crystal_id = crystal_id
        self.protein_id = protein_id
        self.record_time_stamp = record_time_stamp
        self.protein = protein
        self.crystal_compositions = crystal_compositions
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, crystal_id, protein_id, record_time_stamp, protein, crystal_compositions, *args, **kwargs):  # noqa: E501
        """CrystalResponse - a model defined in OpenAPI

        Args:
            crystal_id (int):
            protein_id (int):
            record_time_stamp (datetime):
            protein (PydanticMainProtein):
            crystal_compositions ([CrystalCompositionResponse]):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            diffraction_plan_id (int): [optional]  # noqa: E501
            crystal_uuid (str): [optional]  # noqa: E501
            name (str): [optional]  # noqa: E501
            space_group (str): [optional]  # noqa: E501
            morphology (str): [optional]  # noqa: E501
            color (str): [optional]  # noqa: E501
            size_x (float): [optional]  # noqa: E501
            size_y (float): [optional]  # noqa: E501
            size_z (float): [optional]  # noqa: E501
            cell_a (float): [optional]  # noqa: E501
            cell_b (float): [optional]  # noqa: E501
            cell_c (float): [optional]  # noqa: E501
            cell_alpha (float): [optional]  # noqa: E501
            cell_beta (float): [optional]  # noqa: E501
            cell_gamma (float): [optional]  # noqa: E501
            comments (str): [optional]  # noqa: E501
            pdb_file_name (str): [optional]  # noqa: E501
            pdb_file_path (str): [optional]  # noqa: E501
            abundance (float): [optional]  # noqa: E501
            packing_fraction (float): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.crystal_id = crystal_id
        self.protein_id = protein_id
        self.record_time_stamp = record_time_stamp
        self.protein = protein
        self.crystal_compositions = crystal_compositions
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
