"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from mxcubecore.utils.pyispyb_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from mxcubecore.utils.pyispyb_client.exceptions import ApiAttributeError


def lazy_import():
    from mxcubecore.utils.pyispyb_client.model.beam_line_setup import BeamLineSetup
    globals()['BeamLineSetup'] = BeamLineSetup


class SessionResponse(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'session_id': (int,),  # noqa: E501
            'proposal_id': (int,),  # noqa: E501
            'bltime_stamp': (datetime,),  # noqa: E501
            'exp_session_pk': (int,),  # noqa: E501
            'beam_line_setup_id': (int,),  # noqa: E501
            'project_code': (str,),  # noqa: E501
            'start_date': (datetime,),  # noqa: E501
            'end_date': (datetime,),  # noqa: E501
            'beam_line_name': (str,),  # noqa: E501
            'scheduled': (int,),  # noqa: E501
            'nb_shifts': (int,),  # noqa: E501
            'comments': (str,),  # noqa: E501
            'beam_line_operator': (str,),  # noqa: E501
            'visit_number': (int,),  # noqa: E501
            'used_flag': (int,),  # noqa: E501
            'session_title': (str,),  # noqa: E501
            'structure_determinations': (float,),  # noqa: E501
            'dewar_transport': (float,),  # noqa: E501
            'databackup_france': (float,),  # noqa: E501
            'databackup_europe': (float,),  # noqa: E501
            'operator_site_number': (str,),  # noqa: E501
            'last_update': (datetime,),  # noqa: E501
            'protected_data': (str,),  # noqa: E501
            'external_id': (file_type,),  # noqa: E501
            'nb_reimb_dewars': (int,),  # noqa: E501
            'beam_line_setup': (BeamLineSetup,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'session_id': 'sessionId',  # noqa: E501
        'proposal_id': 'proposalId',  # noqa: E501
        'bltime_stamp': 'bltimeStamp',  # noqa: E501
        'exp_session_pk': 'expSessionPk',  # noqa: E501
        'beam_line_setup_id': 'beamLineSetupId',  # noqa: E501
        'project_code': 'projectCode',  # noqa: E501
        'start_date': 'startDate',  # noqa: E501
        'end_date': 'endDate',  # noqa: E501
        'beam_line_name': 'beamLineName',  # noqa: E501
        'scheduled': 'scheduled',  # noqa: E501
        'nb_shifts': 'nbShifts',  # noqa: E501
        'comments': 'comments',  # noqa: E501
        'beam_line_operator': 'beamLineOperator',  # noqa: E501
        'visit_number': 'visit_number',  # noqa: E501
        'used_flag': 'usedFlag',  # noqa: E501
        'session_title': 'sessionTitle',  # noqa: E501
        'structure_determinations': 'structureDeterminations',  # noqa: E501
        'dewar_transport': 'dewarTransport',  # noqa: E501
        'databackup_france': 'databackupFrance',  # noqa: E501
        'databackup_europe': 'databackupEurope',  # noqa: E501
        'operator_site_number': 'operatorSiteNumber',  # noqa: E501
        'last_update': 'lastUpdate',  # noqa: E501
        'protected_data': 'protectedData',  # noqa: E501
        'external_id': 'externalId',  # noqa: E501
        'nb_reimb_dewars': 'nbReimbDewars',  # noqa: E501
        'beam_line_setup': 'BeamLineSetup',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, session_id, proposal_id, bltime_stamp, *args, **kwargs):  # noqa: E501
        """SessionResponse - a model defined in OpenAPI

        Args:
            session_id (int):
            proposal_id (int):
            bltime_stamp (datetime):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            exp_session_pk (int): [optional]  # noqa: E501
            beam_line_setup_id (int): [optional]  # noqa: E501
            project_code (str): [optional]  # noqa: E501
            start_date (datetime): [optional]  # noqa: E501
            end_date (datetime): [optional]  # noqa: E501
            beam_line_name (str): [optional]  # noqa: E501
            scheduled (int): [optional]  # noqa: E501
            nb_shifts (int): [optional]  # noqa: E501
            comments (str): [optional]  # noqa: E501
            beam_line_operator (str): [optional]  # noqa: E501
            visit_number (int): [optional]  # noqa: E501
            used_flag (int): [optional]  # noqa: E501
            session_title (str): [optional]  # noqa: E501
            structure_determinations (float): [optional]  # noqa: E501
            dewar_transport (float): [optional]  # noqa: E501
            databackup_france (float): [optional]  # noqa: E501
            databackup_europe (float): [optional]  # noqa: E501
            operator_site_number (str): [optional]  # noqa: E501
            last_update (datetime): [optional]  # noqa: E501
            protected_data (str): [optional]  # noqa: E501
            external_id (file_type): [optional]  # noqa: E501
            nb_reimb_dewars (int): [optional]  # noqa: E501
            beam_line_setup (BeamLineSetup): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.session_id = session_id
        self.proposal_id = proposal_id
        self.bltime_stamp = bltime_stamp
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, session_id, proposal_id, bltime_stamp, *args, **kwargs):  # noqa: E501
        """SessionResponse - a model defined in OpenAPI

        Args:
            session_id (int):
            proposal_id (int):
            bltime_stamp (datetime):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            exp_session_pk (int): [optional]  # noqa: E501
            beam_line_setup_id (int): [optional]  # noqa: E501
            project_code (str): [optional]  # noqa: E501
            start_date (datetime): [optional]  # noqa: E501
            end_date (datetime): [optional]  # noqa: E501
            beam_line_name (str): [optional]  # noqa: E501
            scheduled (int): [optional]  # noqa: E501
            nb_shifts (int): [optional]  # noqa: E501
            comments (str): [optional]  # noqa: E501
            beam_line_operator (str): [optional]  # noqa: E501
            visit_number (int): [optional]  # noqa: E501
            used_flag (int): [optional]  # noqa: E501
            session_title (str): [optional]  # noqa: E501
            structure_determinations (float): [optional]  # noqa: E501
            dewar_transport (float): [optional]  # noqa: E501
            databackup_france (float): [optional]  # noqa: E501
            databackup_europe (float): [optional]  # noqa: E501
            operator_site_number (str): [optional]  # noqa: E501
            last_update (datetime): [optional]  # noqa: E501
            protected_data (str): [optional]  # noqa: E501
            external_id (file_type): [optional]  # noqa: E501
            nb_reimb_dewars (int): [optional]  # noqa: E501
            beam_line_setup (BeamLineSetup): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.session_id = session_id
        self.proposal_id = proposal_id
        self.bltime_stamp = bltime_stamp
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
