"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.model.detector import Detector


class TestDetector(unittest.TestCase):
    """Detector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetector(self):
        """Test Detector"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Detector()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
