"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.model.beam_line_setup import BeamLineSetup
globals()['BeamLineSetup'] = BeamLineSetup
from mxcubecore.utils.pyispyb_client.model.session_response import SessionResponse


class TestSessionResponse(unittest.TestCase):
    """SessionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSessionResponse(self):
        """Test SessionResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SessionResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
