"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.model.ssx_sequence_event_create import SSXSequenceEventCreate


class TestSSXSequenceEventCreate(unittest.TestCase):
    """SSXSequenceEventCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSSXSequenceEventCreate(self):
        """Test SSXSequenceEventCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SSXSequenceEventCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
