"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.model.data_collection_response import DataCollectionResponse
globals()['DataCollectionResponse'] = DataCollectionResponse
from mxcubecore.utils.pyispyb_client.model.ssx_data_collection_response import SSXDataCollectionResponse


class TestSSXDataCollectionResponse(unittest.TestCase):
    """SSXDataCollectionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSSXDataCollectionResponse(self):
        """Test SSXDataCollectionResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SSXDataCollectionResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
