"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.model.data_collection_group_response import DataCollectionGroupResponse


class TestDataCollectionGroupResponse(unittest.TestCase):
    """DataCollectionGroupResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataCollectionGroupResponse(self):
        """Test DataCollectionGroupResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DataCollectionGroupResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
