"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.model.laboratory import Laboratory


class TestLaboratory(unittest.TestCase):
    """Laboratory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLaboratory(self):
        """Test Laboratory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Laboratory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
