"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.model.ssx_protein_create import SSXProteinCreate
from mxcubecore.utils.pyispyb_client.model.ssx_sample_component_create import SSXSampleComponentCreate
globals()['SSXProteinCreate'] = SSXProteinCreate
globals()['SSXSampleComponentCreate'] = SSXSampleComponentCreate
from mxcubecore.utils.pyispyb_client.model.ssx_crystal_create import SSXCrystalCreate


class TestSSXCrystalCreate(unittest.TestCase):
    """SSXCrystalCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSSXCrystalCreate(self):
        """Test SSXCrystalCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SSXCrystalCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
