"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.api.lab_contacts_api import LabContactsApi  # noqa: E501


class TestLabContactsApi(unittest.TestCase):
    """LabContactsApi unit test stubs"""

    def setUp(self):
        self.api = LabContactsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_lab_contact(self):
        """Test case for create_lab_contact

        Create Lab Contact  # noqa: E501
        """
        pass

    def test_get_lab_contact(self):
        """Test case for get_lab_contact

        Get Lab Contact  # noqa: E501
        """
        pass

    def test_get_lab_contacts(self):
        """Test case for get_lab_contacts

        Get Lab Contacts  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
