"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.model.crystal_response import CrystalResponse
from mxcubecore.utils.pyispyb_client.model.sample_composition_response import SampleCompositionResponse
globals()['CrystalResponse'] = CrystalResponse
globals()['SampleCompositionResponse'] = SampleCompositionResponse
from mxcubecore.utils.pyispyb_client.model.ssx_sample_response import SSXSampleResponse


class TestSSXSampleResponse(unittest.TestCase):
    """SSXSampleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSSXSampleResponse(self):
        """Test SSXSampleResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SSXSampleResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
