"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.model.sample import Sample
globals()['Sample'] = Sample
from mxcubecore.utils.pyispyb_client.model.paginated_sample import PaginatedSample


class TestPaginatedSample(unittest.TestCase):
    """PaginatedSample unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedSample(self):
        """Test PaginatedSample"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedSample()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
