"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.api.sessions_legacy_with_header_token_api import SessionsLegacyWithHeaderTokenApi  # noqa: E501


class TestSessionsLegacyWithHeaderTokenApi(unittest.TestCase):
    """SessionsLegacyWithHeaderTokenApi unit test stubs"""

    def setUp(self):
        self.api = SessionsLegacyWithHeaderTokenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_sessions(self):
        """Test case for get_sessions

        Get Sessions  # noqa: E501
        """
        pass

    def test_get_sessions_by_dates(self):
        """Test case for get_sessions_by_dates

        Get Sessions By Dates  # noqa: E501
        """
        pass

    def test_get_sessions_for_proposal(self):
        """Test case for get_sessions_for_proposal

        Get Sessions For Proposal  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
