"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.model.pyispyb_core_schemas_events_data_collection_group import PyispybCoreSchemasEventsDataCollectionGroup


class TestPyispybCoreSchemasEventsDataCollectionGroup(unittest.TestCase):
    """PyispybCoreSchemasEventsDataCollectionGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPyispybCoreSchemasEventsDataCollectionGroup(self):
        """Test PyispybCoreSchemasEventsDataCollectionGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PyispybCoreSchemasEventsDataCollectionGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
