"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.model.crystal import Crystal
from mxcubecore.utils.pyispyb_client.model.sample_meta_data import SampleMetaData
globals()['Crystal'] = Crystal
globals()['SampleMetaData'] = SampleMetaData
from mxcubecore.utils.pyispyb_client.model.sample import Sample


class TestSample(unittest.TestCase):
    """Sample unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSample(self):
        """Test Sample"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Sample()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
