"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.model.ssx_sequence_create import SSXSequenceCreate
globals()['SSXSequenceCreate'] = SSXSequenceCreate
from mxcubecore.utils.pyispyb_client.model.ssx_data_collection_create import SSXDataCollectionCreate


class TestSSXDataCollectionCreate(unittest.TestCase):
    """SSXDataCollectionCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSSXDataCollectionCreate(self):
        """Test SSXDataCollectionCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SSXDataCollectionCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
