"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.api.samples_api import SamplesApi  # noqa: E501


class TestSamplesApi(unittest.TestCase):
    """SamplesApi unit test stubs"""

    def setUp(self):
        self.api = SamplesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_sample(self):
        """Test case for get_sample

        Get Sample  # noqa: E501
        """
        pass

    def test_get_samples(self):
        """Test case for get_samples

        Get Samples  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
