"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.model.event import Event
globals()['Event'] = Event
from mxcubecore.utils.pyispyb_client.model.paginated_event import PaginatedEvent


class TestPaginatedEvent(unittest.TestCase):
    """PaginatedEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedEvent(self):
        """Test PaginatedEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
