"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.model.lab_contact import LabContact
globals()['LabContact'] = LabContact
from mxcubecore.utils.pyispyb_client.model.paginated_lab_contact import PaginatedLabContact


class TestPaginatedLabContact(unittest.TestCase):
    """PaginatedLabContact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedLabContact(self):
        """Test PaginatedLabContact"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedLabContact()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
