"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.model.crystal_composition_response import CrystalCompositionResponse
from mxcubecore.utils.pyispyb_client.model.pydantic_main_protein import PydanticMainProtein
globals()['CrystalCompositionResponse'] = CrystalCompositionResponse
globals()['PydanticMainProtein'] = PydanticMainProtein
from mxcubecore.utils.pyispyb_client.model.crystal_response import CrystalResponse


class TestCrystalResponse(unittest.TestCase):
    """CrystalResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCrystalResponse(self):
        """Test CrystalResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CrystalResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
