"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.model.person import Person
globals()['Person'] = Person
from mxcubecore.utils.pyispyb_client.model.lab_contact import LabContact


class TestLabContact(unittest.TestCase):
    """LabContact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLabContact(self):
        """Test LabContact"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LabContact()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
