"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.model.pyispyb_core_schemas_protein_protein import PyispybCoreSchemasProteinProtein
globals()['PyispybCoreSchemasProteinProtein'] = PyispybCoreSchemasProteinProtein
from mxcubecore.utils.pyispyb_client.model.crystal import Crystal


class TestCrystal(unittest.TestCase):
    """Crystal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCrystal(self):
        """Test Crystal"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Crystal()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
