"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.model.person import Person
globals()['Person'] = Person
from mxcubecore.utils.pyispyb_client.model.lab_contact_create import LabContactCreate


class TestLabContactCreate(unittest.TestCase):
    """LabContactCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLabContactCreate(self):
        """Test LabContactCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LabContactCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
