"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from mxcubecore.utils import pyispyb_clientfrom mxcubecore.utils.pyispyb_client.model.laboratory import Laboratory
globals()['Laboratory'] = Laboratory
from mxcubecore.utils.pyispyb_client.model.person import Person


class TestPerson(unittest.TestCase):
    """Person unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPerson(self):
        """Test Person"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Person()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
