---


name: Pages

concurrency:
  group: pages

"on":
  push: null
  pull_request: null

jobs:

  pages-build:

    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          # With shallow clone the "Last updated" timestamp can not get computed
          # See "Caveats" at https://pypi.org/project/sphinx-last-updated-by-git
          fetch-depth: 0

      - name: Setup Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          cache-environment: true
          create-args: >-
            python=${{ matrix.python-version }}
          environment-file: conda-environment-dev.yml
          micromamba-version: 1.5.10-0
          post-cleanup: all

      - name: Install Python dependencies with Poetry
        run: >
          ${MAMBA_EXE} run --name mxcubecore
          poetry install --only=docs,main

      - name: Build documentation with Sphinx
        run: >
          ${MAMBA_EXE} run --name mxcubecore
          make --directory=./docs/ html

      - name: Upload artifact for GitHub Pages
        # This could potentially be run only when we intend to deploy...
        # ...but it can be useful to have the artifact for debugging
        # if: "github.ref_name == github.event.repository.default_branch"
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

  pages-deploy:

    if: github.ref_name == github.event.repository.default_branch

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs:
      - pages-build

    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-24.04

    steps:

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


...
