---

name: Linting & Code Quality

"on":
  pull_request:
    types: [opened, reopened, synchronize]

jobs:

  pre-commit:

    runs-on: ubuntu-24.04

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          cache-environment: true
          create-args: >-
            python=3.10
          environment-file: conda-environment-dev.yml
          post-cleanup: all

      - name: Install Python dependencies
        run: >
          ${MAMBA_EXE} run --name mxcubecore
          poetry install --only=dev

      - name: Run Pre-Commit hooks
        run: >
          ${MAMBA_EXE} run --name mxcubecore
          pre-commit run --all-files --show-diff-on-failure

...
