name: Pytest
on:
  pull_request:
    paths-ignore:
      - "doc/**"
      - "docs/**"
    types: [opened, reopened, synchronize]
jobs:
  Python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          # TODO
          #- "3.8"
          #- "3.9"
          - "3.10"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup conda environment with micromamba for Python ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-environment: true
          create-args: >-
            python=${{ matrix.python-version }}
          environment-file: conda-environment-dev.yml
          post-cleanup: all

      - name: Install dependencies
        run: "${MAMBA_EXE} run --name mxcubecore poetry install --extras=tango --only=dev,main"

      - name: Test with pytest
        run: "${MAMBA_EXE} run --name mxcubecore pytest --no-cov"
